name: sdnext

services:
  api:
    build:
      context: .
      args:
        INSTALLDIR: "/webui"
        RUN_UID: 1000
    command: |
      --listen
      --docs
      --api-only
      --no-download
      --no-half
      --skip-requirements
      --skip-extensions
      --skip-git
      --skip-torch
    # --xformers
    # --no-half-vae
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      DATA_DIR: "./data"
    image: ${REGISTRY:-saladtechnologies}/sdnext:latest
    ports:
      - "7860:7860"
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - model-cache:/webui/data

volumes:
  model-cache:
